# Decide yourself in which git rpository to store your thoughts (Github, Bitbucket, ...)
# Usually it is the same play where you find this file. 
backend:
  name: github
  repo: ChrisLasar/my-thoughts 
