[build.environment]
  HUGO_VERSION = "0.69.0"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"


[[redirects]]
  from = "/notes/:id/:title"
  to = "/notes/:id"
  status = 200
  force = false

[[redirects]]
  from = "/references/:id/:title"
  to = "/references/:id"
  status = 200
  force = false