[build.environment]
  YARN_VERSION = "1.22.4"
  NPM_VERSION = "6.14.4"
  HUGO_VERSION = "0.69.0"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"
