[build.environment]
  HUGO_VERSION = "0.69.0"

[build]
  command = """\
            sed -i s#TT_PLACEHOLDER_REPOSITORY#${REPOSITORY_URL}#g site/config/_default/config.yaml \
            && sed -i s#TT_PLACEHOLDER_BRANCH#${BRANCH}#g site/config/_default/config.yaml \
            && sed -i s#TT_PLACEHOLDER_URL#${URL}#g site/config/_default/config.yaml \
            && yarn build"""

  publish = "dist"

[dev]
#  framework = "#custom"
#  command = "yarn start" # Command to start your dev server
#  port = 8888 # Port that the dev server will be accessible on
#  targetPort = 1313 # Port of target app server
#  publish = "dist" # If you use a _redirect file, provide the path to your static content folder

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "/app/notes/*"
  to = "/app/notes/"
  status = 200
  force = false

[[redirects]]
  from = "/notes/:id/*/"
  to = "/notes/:id"
  status = 200
  force = false

[[redirects]]
  from = "/references/:id/:title"
  to = "/references/:id"
  status = 200
  force = false
