imports:
- path: ../../node_modules/thought-tank
- path: ../../node_modules/@fortawesome/fontawesome-free
  ignoreConfig: true
  disable: false
  mounts:
  - source: svgs
    target: assets/svg/fa-svgs